### PR TITLE
Fixed code

### PR DESCRIPTION
**Pull request by Ezzpify**
I edited your code a bit.
- First of all you can grab the file version from `AssemblyInfo.cs` instead of hard coding it as a variable.
- There's also no real point in adding a user inputted interval, since it doesn't really affect anything how often we check if games are being updated, so I removed that.
- Removed `isDownloading_First` function since it is redundant
- Instead of doing a dirty `try-catch` but not doing anything when catching an exception, I added a simple null check.

Other than that, great idea for a program. Will use it! :+1:

### CODE REVIEW

**Comment by benjibobs** [comment]
> First of all you can grab the file version from AssemblyInfo.cs instead of hard coding it as a variable.

Thank you. I was unaware of this, it makes much more sense

> There's also no real point in adding a user inputted interval, since it doesn't really affect anything how often we check if games are being updated, so I removed that.

Yeh, I probably should've removed this anyway. My original idea was to check filesize of folders so it would have impact on disk activity, but then I decided registry was a much better idea and applicable across multiple steam libraries

> Removed isDownloading_First function since it is redundant

If this function is not called and the user opens the program it will go straight to shutting the computer down - although you can of course cancel it by closing the program. I thought this would cause some frustration for users opening the program to check if it needs to be open before or after the downloads starts

> Instead of doing a dirty try-catch but not doing anything when catching an exception, I added a simple null check.

This certainly seems reasonable, at first I was having some errors with the registry so I added the try catch, but after re-testing the null check it appears to work!

I've noticed your pull request actually deletes SShutdown.cs, renaming it Program.cs - I would much rather you just made the necessary changes to the current code than a rewrite from the ground up! That makes it a lot easier to merge. 

If you resolve the above issues and reply to my point about `isDownloading_First` I'll happily merge :+1: 

You also reference `System.Windows.Forms` which is not actually needed.

Thanks!

**Comment by benjibobs** [comment]
To add to the interval issue, it would appear perhaps [it is a wanted feature](https://www.reddit.com/r/Steam/comments/4wh21k/i_created_an_open_source_and_lightweight_tool/d66zjqt) - it doesn't really hinder the experience so I am unsure whether or not it needs to be removed

**Comment by Ezzpify** [comment]
As for `isDownloading_First` I removed it and instead calling `IsAnythingUpdating` once first to check if an update is going on, and then I loop until it returns false. It's the same logic you used, but instead of calling one function (`isDownloading_First`) which calls the other, I call `IsAnythingUpdating` directly. :) See https://github.com/benjibobs/Steam-Shutdown/pull/1/files#diff-29f9301fb9fe4bb7cda5dfcc64c2c8c6R62 (L62, Program.cs)

I reference `System.Windows.Forms` to access `Application.ProductVersion`. It can be grabbed by checking the executable file version, but this way is more neat imo.

I can re-add the interval since users wanted that.

**Comment by Ezzpify** [comment]
Added back user input

**Comment by benjibobs** [comment]
Yeh, the only problem I have with your implementation is it exits program instead of checking again - it is much easier to press enter than to restart the program (in my opinion anyway) - What do you think about this?

Also note:

> I've noticed your pull request actually deletes SShutdown.cs, renaming it Program.cs - I would much rather you just made the necessary changes to the current code than a rewrite from the ground up! That makes it a lot easier to merge.

**Comment by benjibobs** [comment]
I only mention the end quote because as I add with more commits, your PR still removes that entire class and replaces it with your's rather than changing what is needed

**Comment by Ezzpify** [comment]
Okay, makes sense. Fixed both things,

**Comment by Ezzpify** [comment]
I saw you added different modes (shutdown, restart, sleep) so I added those as well

**Comment by benjibobs** [comment]
Github won't let me merge so [manually merged](https://github.com/benjibobs/Steam-Shutdown/commit/3430d675ab2c7906f263306c09652a6a51fb3d6f)

Will close for now, added you to contributors and please comment with more suggestions if needed or if I missed something!

**Pull request closed without merging**
